apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketdex-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketdex
  template:
    metadata:
      labels:
        app: rocketdex
    spec:
      containers:
      - name: rocketdex-container
        image: rocketdex:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080